news_portal-main/app_news/urls.py
from django.urls import path

from app_news import views


app_name = 'app_news'

urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('moderate_news/', views.ModerateNewsListView.as_view(), name='news_list_moderation'),
    path('personal_news/', views.PersonalNewsListView.as_view(), name='personal_news_list'),
    path('news/<slug:slug>_<int:pk>/', views.NewsDetailCommentCreateView.as_view(), name='news_detail'),
    path('news/<slug:slug>_<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<slug:slug>_<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    path('news/<slug:slug>_<int:pk>/moderate/', views.NewsModerateView.as_view(), name='news_moderation'),
    path('news/create/', views.NewsCreateView.as_view(), name='news_create'),
]

news_portal-main/news/urls.py
from django.contrib import admin
from django.urls import path, include
from project_modules.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main_view'),
    path('admin/', admin.site.urls),
    path('news/', include('app_news.urls')),
    path('users/', include('app_users.urls')),
    path('i18n', include('django.conf.urls.i18n')),
]

news_portal-main/app_news/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from app_news.permissions import PUBLISH_NEWS_PERM_CODE_NAME


class News(models.Model):
    """
    Модель Новостных сводок.
    """
    author = models.ForeignKey(User,
                               on_delete=models.SET_NULL,
                               verbose_name=_('Пользователь'),
                               related_name='news',
                               null=True, )
    title = models.CharField(_('Название'), max_length=100, db_index=True)
    content = models.TextField(_('Содержание'))
    created_at = models.DateTimeField(_('Дата создания'), auto_now_add=True)
    published_at = models.DateTimeField(_('Дата публикации'), null=True, blank=True)
    edited_at = models.DateTimeField(_('Дата редактирования'), auto_now=True)
    is_published = models.BooleanField(_('Статус публикации'), db_index=True, default=False)
    slug = models.SlugField('slug-url')

    class Meta:
        verbose_name = _('Новость')
        verbose_name_plural = _('Новости')
        ordering = ['-created_at']
        permissions = (
            (PUBLISH_NEWS_PERM_CODE_NAME, _("Может публиковать новости")),
        )

    def get_absolute_url(self):
        return reverse('app_news:news_detail', kwargs={'pk': str(self.id), 'slug': self.slug})

    def __str__(self):
        return self.title


class Comment(models.Model):
    """
    Модель комментариев к новостным сводкам
    """
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             verbose_name=_('Пользователь'),
                             related_name='comments',
                             blank=True,
                             null=True, )

    user_name = models.CharField(_('Имя пользователя'),
                                 max_length=100,
                                 db_index=True,
                                 blank=True,
                                 null=True, )
    text = models.TextField(_('Комментарий'))
    news = models.ForeignKey('News',
                             on_delete=models.CASCADE,
                             verbose_name=_('Новость'),
                             related_name='comments', )
    created_at = models.DateTimeField(_('Дата создания'), auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = _('Комментарий')
        verbose_name_plural = _('Комментарии')

    @property
    def get_related_username(self):
        """
        Получение имени пользователя из таблицы User, если такой существует.
        """
        try:
            username = User.objects.get(id=self.user_id).username
        except ObjectDoesNotExist:
            username = None

        return username

    def __str__(self):
        return self.get_related_username or _('{} (аноним)').format(self.user_name)

news_portal-main/app_news/forms.py
from django import forms
from django.forms import modelformset_factory
from django.utils.translation import gettext_lazy as _

from app_news import models
from project_modules.forms import ChangeIsValidFormMixin


class NewsForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма для создания новостной сводки.
    """
    class Meta:
        model = models.News
        exclude = ['author', 'is_published', 'slug', 'published_at']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-field',
                'aria-label': _('Введите название новости'),
            }),
            'content': forms.Textarea(attrs={
                'class': 'form-field form-field_content',
                'aria-label': _('Введите комментарий'),
            }),
        }


class NewsModerateForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма для модерации новостной сводки, управление статусом is_published модели News.
    """

    class Meta:
        model = models.News
        fields = ['is_published']
        widgets = {
            'is_published': forms.CheckboxInput(attrs={
                'class': 'news-verified-status',
                'aria-label': _('Поменять статус публикации'),
                'title': _('Поменять статус публикации'),
            }),
        }


class CommentForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма для создания комментария к новостной сводке.
    """

    def __init__(self, user, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.user = user

    class Meta:
        model = models.Comment
        exclude = ['user', 'news']
        widgets = {
            'user_name': forms.TextInput(attrs={
                'required': '',
                'class': 'form-field',
                'placeholder': _('Введите свое имя'),
                'aria-label': _('Введите свое имя'),
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-field form-field_content',
                'placeholder': _('Введите комментарий'),
                'aria-label': _('Введите комментарий'),
            }),
        }

    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        user_name = cleaned_data['user_name']

        if not self.user.is_authenticated and not user_name:
            self.add_error('user_name', _('Необходимо ввести имя пользователя'))

        return cleaned_data


NewsModerateFormSet = modelformset_factory(models.News, form=NewsModerateForm)

news_portal-main/app_news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.db.models import Prefetch
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from app_news import forms, models
from app_news import services
from app_news.forms import NewsModerateFormSet
from app_users.permissions import user_is_moderator
from app_users.views import ModeratorMixin
from project_modules.views import CustomPaginateListView, BaseFormsetUpdateView


class NewsListBaseView(CustomPaginateListView):
    """
    Базовое представление для вывода списка новостей.
    """
    queryset = models.News.objects.all().prefetch_related('author')
    context_object_name = 'news'
    paginate_cookie_name = 'news_per_page'

    def get_queryset(self):
        queryset = super(NewsListBaseView, self).get_queryset()

        try:
            queryset = services.filter_news_queryset_by_date(queryset, self.request)
        except ValueError:
            raise Http404

        queryset = services.filter_news_queryset_by_title(queryset, self.request)
        queryset = services.filter_news_queryset_by_author(queryset, self.request)

        return queryset


class NewsListView(NewsListBaseView):
    """
    Представление для вывода только активных новостей для всех пользователей.
    """
    def get_queryset(self):
        queryset = super(NewsListView, self).get_queryset()
        queryset = queryset.filter(is_published=True)

        return queryset


class ModerateNewsListView(ModeratorMixin, NewsListBaseView, BaseFormsetUpdateView):
    """
    Представление для вывода новостей только для модераторов (могут видеть все новости).
    И возможностью массово менять статус новости.
    """
    template_name = 'app_news/news_list_moderation.html'
    formset = NewsModerateFormSet

    def get_queryset(self):
        queryset = super(ModerateNewsListView, self).get_queryset()
        queryset = services.filter_news_queryset_by_activity(queryset, self.request)

        return queryset


class PersonalNewsListView(LoginRequiredMixin, NewsListBaseView):
    """
    Представление для вывода личных новостей пользователя.
    """
    template_name = 'app_news/personal_news_list.html'

    def get_queryset(self):
        queryset = super(PersonalNewsListView, self).get_queryset()
        queryset = queryset.filter(author=self.request.user)
        queryset = services.filter_news_queryset_by_activity(queryset, self.request)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(PersonalNewsListView, self).get_context_data(*args, **kwargs)
        context['news_successfully_delete'] = self.request.GET.get('news_successfully_delete')
        context['deleted_news_title'] = self.request.GET.get('deleted_news_title')

        return context


class NewsDetailCommentCreateView(generic.DetailView, generic.FormView):
    """
    Представление для отображения детальной информации о новости,
    включая все комментарии к новости, и возможностью добавления нового комментария.
    """
    queryset = models.News.objects.prefetch_related(
        Prefetch('comments', queryset=models.Comment.objects.order_by('-created_at'), to_attr='all_comments'),
    )
    context_object_name = 'news'
    form_class = forms.CommentForm
    query_pk_and_slug = True

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()

        if not self.object.is_published:
            if user_is_moderator(request.user) and not self.object.author == request.user:
                return redirect(
                    reverse('app_news:news_moderation', kwargs={'pk': self.object.pk, 'slug': self.object.slug}))
            else:
                return redirect(
                    reverse('app_news:news_update', kwargs={'pk': self.object.pk, 'slug': self.object.slug}))

        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

    def get_form_kwargs(self):
        kwargs = super(NewsDetailCommentCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user

        return kwargs

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(NewsDetailCommentCreateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        services.create_comment(form, self.request, self.object)
        return super(NewsDetailCommentCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('app_news:news_detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


class UserVerificationMixin(LoginRequiredMixin, PermissionRequiredMixin):
    """
    Миксин верификации пользователя, должен быть аутентифицирован и и меть определенные права.
    """
    login_url = reverse_lazy('app_users:login')
    permission_required = ['app_news.add_news', 'app_news.change_news', 'app_news.delete_news', 'app_news.view_news']


class NewsCreateView(UserVerificationMixin, generic.CreateView):
    """
    Представление создания новости.
    """
    template_name = 'app_news/news_create.html'
    form_class = forms.NewsForm

    def form_valid(self, form):
        self.object = services.create_news(form, self.request)

        return super(generic.CreateView, self).form_valid(form)


class NewsDeleteUpdateMixin(UserVerificationMixin, UserPassesTestMixin):
    template_name = 'app_news/news_update.html'
    model = models.News
    context_object_name = 'news'

    def test_func(self):
        active_user = self.request.user
        self.object = self.get_object()

        return self.object.author == active_user


class NewsDeleteView(NewsDeleteUpdateMixin, generic.DeleteView):
    """
    Представление удаления новости.
    """
    success_url = reverse_lazy('app_news:personal_news_list')

    def get_success_url(self):
        url = super(NewsDeleteView, self).get_success_url()
        return f"{url}?news_successfully_delete=True&deleted_news_title={self.object.title}"


class NewsUpdateView(NewsDeleteUpdateMixin, generic.UpdateView):
    """
    Представление изменения новости.
    """
    form_class = forms.NewsForm

    def form_valid(self, form):
        self.object = services.update_news(form)

        return super(generic.UpdateView, self).form_valid(form)


class NewsModerateView(ModeratorMixin, generic.UpdateView):
    """
    Модерация новости, добавление статуса активности.
    """
    template_name = 'app_news/news_moderation.html'
    form_class = forms.NewsModerateForm
    model = models.News
    context_object_name = 'news'

news_portal-main/app_news/templates/app_news/news_create.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Создать новостную сводку' %}
{% endblock %}

{% block content %}
    {% trans 'Создать новостную сводку'  as create_news_trans %}
    {% with title_name=create_news_trans %}
        <h2>{{ title_name }}</h2>

        <form method="post" action="{% url 'app_news:news_create' %}">
            {% include 'app_news/templates_for_include/base_news_template_form.html' %}

            <div class="update-news">
                <button type="submit" aria-label="{{ title_name }}" title="{{ title_name }}">{{ title_name }}</button>
            </div>

        </form>
    {% endwith %}
{% endblock %}

news_portal-main/app_news/templates/app_news/news_detail.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% load app_users_templatetags %}

{% block title %}
    {% trans 'Детальная информация о новости' %} {{ news }}
{%  endblock %}


{% block content %}
    <h2>{{ news.title }}</h2>
    <div class="single-news-edit-links">
        {% if request.user == news.author%}
            {% url 'app_news:news_update' pk=news.id slug=news.slug as news_update_path %}
            {% trans 'Редактировать новость' as edit_news_trans %}
            <a href="{{ news_update_path }}" class="update-link" aria-label="{{ edit_news_trans }}" title="{{ edit_news_trans }}">{{ edit_news_trans }}</a>
            <form method="post" action="{% url 'app_news:news_delete' pk=news.id slug=news.slug %}">
                {% csrf_token %}
                <button type="submit">{% trans 'Удалить новость' %}</button>
            </form>
        {% endif %}
        {% if request.user|is_moderator %}
            {% url 'app_news:news_moderation' pk=news.id slug=news.slug as news_moderate_path %}
            {% trans 'Модерация новости' as news_moder_trans %}
            <a class="update-link" href="{{ news_moderate_path }}" aria-label="{{ news_moder_trans }}" title="{{ news_moder_trans }}">{{ news_moder_trans }}</a>
        {% endif %}
    </div>

    {% include 'app_news/templates_for_include/news_content.html' %}

    <h2>{% trans 'Комментарии' %}</h2>
    <ol class="news-comments">
        {% for comment in news.all_comments %}
            <li class="news-comments__item">
                <div class="comment-content">
                    <p class="comment-content__item">{% trans 'Автор' %}: {{ comment }}</p>
                    <p class="comment-content__item comment-content__item_text">{{ comment.text }}</p>
                    <p class="content-info">{% trans 'Дата публикации' %}: {{ comment.created_at }}</p>
                </div>
            </li>
        {% empty %}
            <div class="comment-content">
                <p class="comment-content__item">{% trans 'Комментариев пока что нету, вы можете стать первым' %}</p>
            </div>
        {% endfor %}
    </ol>

    <h2>{% trans 'Добавить комментарий' %}</h2>
    <form method="post" action="{% url 'app_news:news_detail' pk=news.pk slug=news.slug%}">
        {% csrf_token %}
        {{ form.non_field_errors }}

        {% if not request.user.is_authenticated %}

            <p>
                {{ form.user_name.label_tag }}
                {{ form.user_name.errors }}
                {{ form.user_name }}
            </p>

        {% endif %}

        {% include 'project_modules/templates_for_include/scroling_to_field_with_errors.html' with label_id=form.text.id_for_label %}

        <p>
            {{ form.text.label_tag }}
            {{ form.text.errors }}
            {{ form.text }}
        </p>

        {% trans 'Опубликовать комментарий' as publish_comment_trans %}
        <button type="submit" aria-label="{{ publish_comment_trans }}" title="{{ publish_comment_trans }}">{{ publish_comment_trans }}</button>
    </form>

{% endblock %}

news_portal-main/app_news/templates/app_news/news_list.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
        {% trans 'Все новости со всех концов света' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Все новости' %}</h2>

    {% include 'app_news/templates_for_include/accessible_news_filters.html' %}
    {% include 'app_news/templates_for_include/base_news_list.html' %}

{% endblock %}

news_portal-main/app_news/templates/app_news/news_list_moderation.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% load app_news_templatetags %}

{% block title %}
        {% trans 'Модерация новостей' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Новости для модерации' %}</h2>

    {% include 'app_news/templates_for_include/accessible_news_filters.html' %}
    {% include 'app_news/templates_for_include/activity_news_filter.html' %}
    {% include 'project_modules/templates_for_include/set_links_for_object_list_paginator.html' %}

    {% if news %}
        <form method="post" action="{{ request.get_full_path }}">
        {% csrf_token %}
        {{ formset.management_form }}
            {% include 'project_modules/templates_for_include/moderator_objects_paginator_links_list.html' %}

            <div>
                <ol class="object-list" start="{{ page_obj.start_index }}">
                    {% for single_news, single_form in news|zip_lists:formset %}
                        {% include 'app_news/templates_for_include/news_list_item.html' %}
                    {% endfor %}
                </ol>
            </div>

            {% include 'project_modules/templates_for_include/moderator_objects_paginator_links_list.html' %}
        </form>

    {% else %}
        <h2>{% trans 'Нет новостей, удовлетворяющих вашему запросу' %}</h2>
    {% endif %}

{% endblock %}

news_portal-main/app_news/templates/app_news/news_moderation.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Модерация новости' %}
{% endblock %}

{% block content %}
    {% trans 'Модерация новости' as moder_news_trans %}
    {% with title_name=moder_news_trans|add:' '|add:news.title %}
        <h2>{{ title_name }}</h2>

        {% include 'app_news/templates_for_include/news_content.html' %}

        <form method="post" action="{% url 'app_news:news_moderation' pk=news.id slug=news.slug %}">
            {% include 'app_news/templates_for_include/base_news_template_form.html' %}

            <div class="update-news">
                <button type="submit" aria-label="{{ title_name }}" title="{{ title_name }}">{{ title_name }}</button>
            </div>

        </form>
    {% endwith %}
{% endblock %}

news_portal-main/app_news/templates/app_news/news_update.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% load app_users_templatetags %}

{% block title %}
        {% trans 'Редактировать новость' %} {{ news.title }}
{% endblock %}

{% block content %}
    {% trans 'Редактировать новость' as edit_news_trans %}
    {% with title_name=edit_news_trans|add:' '|add:news.title %}
        <h2>{{ title_name }}</h2>

        <form method="post" action="{% url 'app_news:news_update' pk=news.id slug=news.slug %}">
            {% include 'app_news/templates_for_include/base_news_template_form.html' %}

            <div class="update-news">
                {% if news.is_published %}
                    <button id="change-news-confirm-button" type="button" aria-label="{{ title_name }}" title="{{ title_name }}">{{ title_name }}</button>
                    <div class="update-news__confirm-wrap">
                        <div class="update-news__confirm-container">
                            <p>{% trans 'Если вы внесли изменения, после подтверждения новость станет неактивной, вы уверены что, хотите применить изменения?' %}</p>
                            <div class="update-news__confirm-buttons">
                                {% trans 'Да' as yes_trans %}
                                <button type="submit" aria-label="{{ yes_trans }}" title="{{ yes_trans }}">{{ yes_trans }}</button>
                                {% trans 'Нет' as no_trans %}
                                <button id="change-news-confirm-button-no" type="button" aria-label="{{ no_trans }}" title="{{ no_trans }}">{{ no_trans }}</button>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <button type="submit" aria-label="{{ title_name }}" title="{{ title_name }}">{{ title_name }}</button>
                {% endif %}

                {% if request.user|is_moderator %}
                    {% url 'app_news:news_moderate' pk=news.id slug=news.slug as news_moderate_path %}
                    {% trans 'Модерация новости' as moder_news_trans %}
                    <a class="update-link" href="{{ news_moderate_path }}" aria-label="{{ moder_news_trans }}" title="{{ moder_news_trans }}">{{ moder_news_trans }}</a>
                {% endif %}
            </div>
        </form>

        <div class="update-news">
            <form method="post" action="{% url 'app_news:news_delete' pk=news.id slug=news.slug %}">

                {% csrf_token %}
                <button type="submit">{% trans 'Удалить новость' %}</button>
            </form>
        </div>
    {% endwith %}
{% endblock %}

news_portal-main/app_news/templates/app_news/personal_news_list.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
        {% trans 'Личные новости' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Ваши новости' %}</h2>
    {% if news_successfully_delete %}
        <h2>{% trans 'Новость' %} {{ deleted_news_title }} {% trans 'успешно удалена' %}</h2>
    {% endif %}

    {% include 'app_news/templates_for_include/accessible_news_filters.html' %}
    {% include 'app_news/templates_for_include/activity_news_filter.html' %}
    {% include 'app_news/templates_for_include/base_news_list.html' %}

{% endblock %}