news_portal-main/app_news/urls.py
from django.urls import path

from app_news import views


app_name = 'app_news'

urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('moderate_news/', views.ModerateNewsListView.as_view(), name='news_list_moderation'),
    path('personal_news/', views.PersonalNewsListView.as_view(), name='personal_news_list'),
    path('news/<slug:slug>_<int:pk>/', views.NewsDetailCommentCreateView.as_view(), name='news_detail'),
    path('news/<slug:slug>_<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<slug:slug>_<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    path('news/<slug:slug>_<int:pk>/moderate/', views.NewsModerateView.as_view(), name='news_moderation'),
    path('news/create/', views.NewsCreateView.as_view(), name='news_create'),
]

news_portal-main/app_users/urls.py
from django.urls import path

from app_users import views


app_name = 'app_users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('change_password/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update_telephone/', views.UserProfileTelephoneUpdateView.as_view(), name='update_telephone'),
    path('profile/<int:pk>/update_city/', views.UserProfileCityUpdateView.as_view(), name='update_city'),
    path('profile/<int:pk>/update_username/', views.UserUsernameUpdateView.as_view(), name='update_username'),
    path('profile/<int:pk>/update_email/', views.UserEmailUpdateView.as_view(), name='update_email'),
    path('profile/<int:pk>/moderate/', views.UserModerateView.as_view(), name='user_moderation'),
    path('moderate/', views.ModeratorMainView.as_view(), name='main_moderator'),
    path('moderate_users/', views.ModerateUsersListView.as_view(), name='users_list_moderation'),
]

news_portal-main/news/urls.py
from django.contrib import admin
from django.urls import path, include
from project_modules.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main_view'),
    path('admin/', admin.site.urls),
    path('news/', include('app_news.urls')),
    path('users/', include('app_users.urls')),
    path('i18n', include('django.conf.urls.i18n')),
]

news_portal-main/project_modules/forms.py
from django.forms import BaseForm


class ChangeIsValidFormMixin(BaseForm):
    """
    Форма добавляет CSS-класс 'invalid_field' полям, у которых есть ошибка.
    """

    def is_valid(self):
        result = super(ChangeIsValidFormMixin, self).is_valid()

        for field_name in (self.fields if '__all__' in self.errors else self.errors):
            attrs = self.fields[field_name].widget.attrs
            attrs.update({'class': attrs.get('class', '') + ' invalid_field'})
        return result

news_portal-main/project_modules/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.base import ContextMixin

from app_users.permissions import user_is_moderator


class MainView(generic.TemplateView):
    """
    Страница приветствия.
    """
    template_name = 'project_modules/index.html'


class CustomPaginateListView(generic.ListView):
    """
    Базовое представление c кастомной пагинацией.
    """
    paginate_by = 10
    paginate_cookie_name = 'objects_per_page'

    def get_paginate_by(self, queryset):
        try:
            objects_per_page = int(self.request.COOKIES.get(self.paginate_cookie_name))
            return objects_per_page
        except (ValueError, TypeError):
            pass

        return self.paginate_by

    def paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(
            queryset, page_size, orphans=self.get_paginate_orphans(),
            allow_empty_first_page=self.get_allow_empty())
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(page_kwarg) or self.request.GET.get(page_kwarg) or 1
        page = paginator.get_page(page)

        return paginator, page, page.object_list, page.has_other_pages()


class ModeratorMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Базовый класс для пользователя-модератора сайта.
    """
    login_url = reverse_lazy('app_users:login')

    def test_func(self):
        return user_is_moderator(self.request.user)


class BaseFormsetUpdateView(ContextMixin):
    formset = None

    def get_formset_kwargs(self, context):
        formset_kwargs = {'queryset': context[self.context_object_name]}

        if self.request.method in ('POST', 'PUT'):
            formset_kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })

        return formset_kwargs

    def get_formset(self, context):
        formset_kwargs = self.get_formset_kwargs(context)
        self.formset = self.formset(**formset_kwargs)

        return self.formset

    def get_context_data(self, *args, **kwargs):
        context = super(BaseFormsetUpdateView, self).get_context_data(*args, **kwargs)
        context['formset'] = self.get_formset(context)

        return context

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data()

        if self.formset.is_valid():
            self.formset.save()
            return HttpResponseRedirect(request.get_full_path())
        else:
            return self.render_to_response(context)

news_portal-main/project_modules/templates/project_modules/templates_for_include/moderator_objects_paginator_links_list.html
{% load i18n %}

<div class="object-list-control">
    {% include 'project_modules/templates_for_include/object_paginator_links_list.html' %}
    <button type="submit" class="objects-list-control__submit-button">{% trans 'Применить установленные статусы' %}</button>
</div>

news_portal-main/project_modules/templates/project_modules/templates_for_include/moderator_submenu_links_list.html
{% load i18n %}

<li class="nav-list__item nav-list__item_moderator {{ nav_list__item_moderator }}">
    {% trans 'Меню модерации' as menu_moder_trans%}
    <a href="{% url 'app_users:main_moderator' %}" aria-label="{{ menu_moder_trans }}" title="{{ menu_moder_trans }}">{{ menu_moder_trans }}</a>
    <ul class="submenu {{ nav_list_submenu }}">
        {% trans 'Модерация пользователей' as users_moder_trans%}
        <li class="submenu__item {{ nav_list_submenu_item }}"><a href="{% url 'app_users:users_list_moderation' %}" aria-label="{{ users_moder_trans }}" title="{{ users_moder_trans }}">{{ users_moder_trans }}</a>
        {% trans 'Модерация новостей' as news_moder_trans%}
        <li class="submenu__item {{ nav_list_submenu_item }}"><a href="{% url 'app_news:news_list_moderation' %}" aria-label="{{ news_moder_trans }}" title="{{ news_moder_trans }}">{{ news_moder_trans }}</a>
    </ul>

news_portal-main/project_modules/templates/project_modules/templates_for_include/nav_app_users_links.html
{% load i18n %}

{% if request.user.is_authenticated %}
    {% trans 'Покинуть сайт' as logout_trans%}
    <a href="{% url 'app_users:logout' %}?next={{ request.path }}" class="{{ class }}" aria-label="{{ logout_trans }}" title="{{ logout_trans }}">{{ logout_trans }}</a>
    {% url 'app_users:profile' as user_profile_url %}
    {% if top_menu_flag %}
        <div class="personal-account-links-container">
            {% trans 'Личный кабинет' as personal_account_trans %}
            <a href="{{ user_profile_url }}"  class="{{ class }}" aria-label="{{ personal_account_trans }}" title="{{ personal_account_trans }}">{{ personal_account_trans }}</a>
            <ul class="submenu submenu_personal-account-links">
                {% trans 'Мои новости' as my_news_trans %}
                <li class="submenu__item submenu__item_color_white"><a href="{% url 'app_news:personal_news_list' %}" aria-label="{{ my_news_trans }}" title="{{ my_news_trans }}">{{ my_news_trans }}</a>
            </ul>
        </div>
    {% else %}
        {% trans 'Личный кабинет' as personal_account_trans %}
         <a href="{{ user_profile_url }}"  class="{{ class }}" aria-label="{{ personal_account_trans }}" title="{{ personal_account_trans }}">{{ personal_account_trans }}</a>
    {% endif %}
{% else %}
    {% trans 'Войти на сайт' as login_trans %}
    <a href="{% url 'app_users:login' %}" class="{{ class }}" aria-label="{{ login_trans }}" title="{{ login_trans }}">{{ login_trans }}</a>
{% endif %}

news_portal-main/project_modules/templates/project_modules/templates_for_include/nav_by_site.html
{% load i18n %}
{% load app_users_templatetags %}

<nav>
    <ul class="nav-list">
        {% url 'main_view' as main_path %}
        {% if main_path != request.path %}
            {% trans 'На главную страницу' as to_main_page_trans %}
            <li class="nav-list__item"><a href="{{ main_path }}" aria-label="{{ to_main_page_trans }}" title="{{ to_main_page_trans }}">{{ to_main_page_trans }}</a>
        {% endif %}

        {% url 'app_news:news_list' as news_list_path %}
        {% if news_list_path != request.path %}
            {% trans 'Все новости' as all_news_trans %}
            <li class="nav-list__item"><a href="{{ news_list_path }}" aria-label="{{ all_news_trans }}" title="{{ all_news_trans }}">{{ all_news_trans }}</a>
        {% endif %}

        {% url 'app_news:news_create' as create_news_path %}
        {% if create_news_path != request.path and request.user.profile.is_verified%}
            {% trans 'Создать новостную сводку' as create_news_trans %}
            <li class="nav-list__item"><a href="{{ create_news_path }}" aria-label="{{ create_news_trans }}" title="{{ create_news_trans }}">{{ create_news_trans }}</a>
        {% endif %}

        {% if request.user|is_moderator%}
                {% if top_menu_flag %}
                    {% include 'project_modules/templates_for_include/moderator_submenu_links_list.html' with nav_list_submenu='submenu_header' nav_list_submenu_item='submenu__item_color' %}
                {% else %}
                    {% include 'project_modules/templates_for_include/moderator_submenu_links_list.html' with nav_list_submenu='submenu_footer' nav_list_submenu_item='submenu__item_color_white' nav_list__item_moderator='nav-list__item_moderator_white'%}
                {% endif %}
        {% endif %}
    </ul>
</nav>

news_portal-main/project_modules/templates/project_modules/templates_for_include/object_paginator_links_list.html
{% load i18n %}
{% load app_news_templatetags %}

{% if page_obj.has_other_pages %}
    <div class="paginate-objects">
        <nav class="paginate-objects__container">
            <ul class="paginate-objects__links-list">
                {% with visible_pages=2 %}
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <li class="paginate-objects__link paginate-objects__link_visible_page">{{ p }}</li>
                        {% elif p >= page_obj.number|subtract:visible_pages and p <= page_obj.number|add:visible_pages  %}
                            {% include 'project_modules/templates_for_include/single_link_in_objects_paginator.html' with p=p text=p%}
                        {% elif p == 1 %}
                            {% include 'project_modules/templates_for_include/single_link_in_objects_paginator.html' with p=p text=p%}
                            {% if page_obj.number > visible_pages|add:2 %}
                                <li class="paginate-objects__link">
                                    ...
                                </li>
                            {% endif %}
                        {% elif p == paginator.num_pages %}
                            {% if page_obj.number < paginator.num_pages|subtract:visible_pages|subtract:1 %}
                                <li class="paginate-objects__link">
                                    ...
                                </li>
                            {% endif %}
                            {% include 'project_modules/templates_for_include/single_link_in_objects_paginator.html' with p=p text=p%}
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </ul>
        </nav>
        <div>
            <nav class="paginate-objects__container">
                <ul class="paginate-objects__links-list">
                    {% if page_obj.has_previous %}
                        {% trans 'Предыдущая'  as prev_trans%}
                        {% include 'project_modules/templates_for_include/single_link_in_objects_paginator.html' with p=page_obj.previous_page_number text=prev_trans %}
                    {% endif %}
                    {% if page_obj.has_next %}
                        {% trans 'Следующая'  as next_trans%}
                        {% include 'project_modules/templates_for_include/single_link_in_objects_paginator.html' with p=page_obj.next_page_number text=next_trans %}
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endif %}

news_portal-main/project_modules/templates/project_modules/templates_for_include/scroling_to_field_with_errors.html
{% if form.errors %}
    <script>
      document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("{{ label_id }}").scrollIntoView();
        window.scrollBy(0,-200)
      });
    </script>
{% endif %}

news_portal-main/project_modules/templates/project_modules/templates_for_include/set_links_for_object_list_paginator.html
{% load static %}

<script type="module">
    import {getNewQuery} from '{% static 'project_modules/js/change_query_string.js' %}';

    document.addEventListener("DOMContentLoaded", function () {
        // Установка ссылок для пагинатора.
        let new_page_links = document.querySelectorAll('a[page_number]');

        for (let new_page_link of new_page_links) {
            let params = {
                'page': new_page_link.getAttribute('page_number'),
            }
            new_page_link.href = getNewQuery(params)
        }
    });
</script>

news_portal-main/project_modules/templates/project_modules/templates_for_include/single_link_in_objects_paginator.html
<li class="paginate-objects__link">
    <a page_number="{{ p }}" class="update-link" href="">{{ text }}</a>
</li>