news_portal-main/app_news/urls.py
from django.urls import path

from app_news import views


app_name = 'app_news'

urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('moderate_news/', views.ModerateNewsListView.as_view(), name='news_list_moderation'),
    path('personal_news/', views.PersonalNewsListView.as_view(), name='personal_news_list'),
    path('news/<slug:slug>_<int:pk>/', views.NewsDetailCommentCreateView.as_view(), name='news_detail'),
    path('news/<slug:slug>_<int:pk>/update/', views.NewsUpdateView.as_view(), name='news_update'),
    path('news/<slug:slug>_<int:pk>/delete/', views.NewsDeleteView.as_view(), name='news_delete'),
    path('news/<slug:slug>_<int:pk>/moderate/', views.NewsModerateView.as_view(), name='news_moderation'),
    path('news/create/', views.NewsCreateView.as_view(), name='news_create'),
]

news_portal-main/app_users/urls.py
from django.urls import path

from app_users import views


app_name = 'app_users'

urlpatterns = [
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', views.LogoutUserView.as_view(), name='logout'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('change_password/', views.UserChangePasswordView.as_view(), name='change_password'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/update_telephone/', views.UserProfileTelephoneUpdateView.as_view(), name='update_telephone'),
    path('profile/<int:pk>/update_city/', views.UserProfileCityUpdateView.as_view(), name='update_city'),
    path('profile/<int:pk>/update_username/', views.UserUsernameUpdateView.as_view(), name='update_username'),
    path('profile/<int:pk>/update_email/', views.UserEmailUpdateView.as_view(), name='update_email'),
    path('profile/<int:pk>/moderate/', views.UserModerateView.as_view(), name='user_moderation'),
    path('moderate/', views.ModeratorMainView.as_view(), name='main_moderator'),
    path('moderate_users/', views.ModerateUsersListView.as_view(), name='users_list_moderation'),
]

news_portal-main/news/urls.py
from django.contrib import admin
from django.urls import path, include
from project_modules.views import MainView


urlpatterns = [
    path('', MainView.as_view(), name='main_view'),
    path('admin/', admin.site.urls),
    path('news/', include('app_news.urls')),
    path('users/', include('app_users.urls')),
    path('i18n', include('django.conf.urls.i18n')),
]

news_portal-main/app_users/forms.py
import re

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.forms import modelformset_factory
from django.utils.translation import gettext_lazy as _

from project_modules.forms import ChangeIsValidFormMixin
from app_users import models


LOGIN_REGISTER_UPDATE_FIELD_CLASS = 'login-register-update-field'

PASSWORD_HELP_TEXT = _("Пароль не должен быть слишком похож на другую вашу личную информацию. Ваш "
                       "пароль должен содержать как минимум 8 символов. Такой пароль часто "
                       "используется. Пароль не может состоять только из цифр.")


class CleanedUserProfileTelephoneMixin:
    """
    Миксин для проверки поля telephone модели UserProfile.
    """

    def clean_telephone(self):
        telephone = self.cleaned_data['telephone']
        telephone_digits = re.sub(r'\D', '', telephone)

        if telephone.startswith('8'):
            telephone = f'+7{telephone_digits[1:]}'
        else:
            telephone = f'+{telephone_digits}'

        user_with_telephone = models.UserProfile.objects.filter(telephone=telephone)

        if user_with_telephone.exists():
            if user_with_telephone.filter(pk=self.instance.id).exists():
                error_message = _('Это ваш номер телефона, пожалуйста введите другой')
            else:
                error_message = _('Пользователь с таким номером уже существует')
            self.add_error('telephone', error_message)

        return telephone


class CleanedUserEmailMixin:
    """
    Миксин для проверки поля email модели User.
    """

    def clean_email(self):
        email = self.cleaned_data['email']
        users_with_email = User.objects.filter(email=email)

        if not email:
            self.add_error('email', _('Необходимо ввести адрес электронной почты'))
        elif users_with_email.exists():
            if users_with_email.filter(pk=self.instance.id).exists():
                error_message = _('Это ваш Email, пожалуйста введите другой')
            else:
                error_message = _('Пользователь с таким E-mail уже существует')
            self.add_error('email', error_message)

        return email


class AuthForm(AuthenticationForm, ChangeIsValidFormMixin):
    """
    Форма аутентификации пользователя.
    """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            'autofocus': True,
            'placeholder': _('Введите логин'),
            'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS,
        }),
    )
    password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'current-password',
            'placeholder': _('Введите пароль'),
            'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS,
        }),
    )


class UserChangePasswordForm(PasswordChangeForm, ChangeIsValidFormMixin):
    """
    Форма смены пароля пользователя.
    """
    prefix = 'change_password_form'

    def __init__(self, *args, **kwargs):
        super(UserChangePasswordForm, self).__init__(*args, **kwargs)

        self.fields['old_password'].help_text = _('Введите ваш старый пароль')
        self.fields['new_password1'].help_text = PASSWORD_HELP_TEXT
        self.fields['new_password2'].help_text = _('Повторите пароль')

        for field in self.fields.values():
            field.widget.attrs.update({'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS,
                                       'title': field.help_text, })

        self.fields['old_password'].widget.attrs.update({'placeholder': _('Введите старый пароль'),
                                                         'aria-label': _('Введите старый пароль'), })
        self.fields['new_password1'].widget.attrs.update({'placeholder': _('Введите новый пароль'),
                                                          'aria-label': _('Введите новый пароль'), })
        self.fields['new_password2'].widget.attrs.update({'placeholder': _('Повторите пароль'),
                                                          'aria-label': _('Повторите пароль'), })


class RegisterForm(UserCreationForm, ChangeIsValidFormMixin, CleanedUserProfileTelephoneMixin, CleanedUserEmailMixin):
    """
    Форма регистрации пользователя.
    """
    telephone = forms.CharField(max_length=20,
                                required=True,
                                help_text=_('Введите ваш номер телефона'), )

    telephone.widget.attrs.update({'placeholder': _('Номер телефона'),
                                   'type': 'tel',
                                   'aria-label': _('Введите ваш номер телефона'),
                                   'data-tel-input': '', })

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['email'].help_text = _('Адрес электронной почты должен содержать "@"')
        self.fields['password1'].help_text = PASSWORD_HELP_TEXT

        for field in self.fields.values():
            field.widget.attrs.update({'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS,
                                       'title': f'{field.help_text}', })

        self.fields['username'].widget.attrs.update({'placeholder': _('Логин'),
                                                     'aria-label': _('Введите ваш логин'), })
        self.fields['email'].widget.attrs.update({'placeholder': 'E-mail',
                                                  'aria-label': _('Введите ваш e-mail'), })
        self.fields['password1'].widget.attrs.update({'placeholder': _('Введите пароль'),
                                                      'aria-label': _('Введите пароль'), })
        self.fields['password2'].widget.attrs.update({'placeholder': _('Повторите пароль'),
                                                      'aria-label': _('Повторите пароль'), })

    class Meta:
        model = User
        fields = ('username', 'email', 'telephone', 'password1', 'password2',)


class UserProfileTelephoneForm(forms.ModelForm, ChangeIsValidFormMixin, CleanedUserProfileTelephoneMixin):
    """
    Форма смены телефона пользователя
    """
    prefix = 'telephone_form'

    def __init__(self, *args, **kwargs):
        super(UserProfileTelephoneForm, self).__init__(*args, **kwargs)

        self.fields['telephone'].widget.attrs.update({'placeholder': _('Введите новый номер телефона'),
                                                      'type': 'tel',
                                                      'aria-label': _('Введите ваш номер телефона'),
                                                      'title': _('Введите ваш номер телефона'),
                                                      'data-tel-input': '',
                                                      'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS, })

    class Meta:
        model = models.UserProfile
        fields = ('telephone',)


class UserProfileCityForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма смены города пользователя
    """
    prefix = 'city_form'

    def __init__(self, *args, **kwargs):
        super(UserProfileCityForm, self).__init__(*args, **kwargs)

        self.fields['city'].widget.attrs.update({'placeholder': _('Введите новый город'),
                                                 'aria-label': _('Введите новый город'),
                                                 'title': _('Введите новый город'),
                                                 'required': True,
                                                 'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS, })

    def clean_city(self):
        city = self.cleaned_data['city']

        if not city:
            self.add_error('city', _('Введите пожалуйста название города'))

        return city

    class Meta:
        model = models.UserProfile
        fields = ('city',)


class UserUsernameForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма смены имени пользователя
    """
    prefix = 'username_form'

    def __init__(self, *args, **kwargs):
        super(UserUsernameForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'placeholder': _('Введите новый логин'),
                                                     'aria-label': _('Введите новый логин'),
                                                     'title': _('Введите новый логин'),
                                                     'required': True,
                                                     'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS, })

    class Meta:
        model = User
        fields = ('username',)


class UserEmailForm(forms.ModelForm, ChangeIsValidFormMixin, CleanedUserEmailMixin):
    """
    Форма смены e-mail пользователя
    """
    prefix = 'email_form'

    def __init__(self, *args, **kwargs):
        super(UserEmailForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update({'placeholder': _('Введите новый email'),
                                                  'aria-label': _('Введите новый email'),
                                                  'title': _('Введите новый email'),
                                                  'required': True,
                                                  'class': LOGIN_REGISTER_UPDATE_FIELD_CLASS, })

    class Meta:
        model = User
        fields = ('email',)


class UserProfileVerificationForm(forms.ModelForm, ChangeIsValidFormMixin):
    """
    Форма верификации пользователя
    """

    class Meta:
        model = models.UserProfile
        fields = ('is_verified',)
        widgets = {
            'is_verified': forms.CheckboxInput(attrs={
                'class': 'user-verified-status',
                'aria-label': _('Поменять статус верификации'),
                'title': _('Поменять статус верификации'),
            }),
        }

news_portal-main/app_users/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views.generic import FormView, TemplateView, UpdateView

from app_users import forms
from app_users import models
from app_users.forms import UserProfileModerateFormSet
from app_users import services
from project_modules.views import CustomPaginateListView, ModeratorMixin, BaseFormsetUpdateView


class LoginUserView(LoginView):
    """
    Вход на сайт под своим пользователем.
    """
    form_class = forms.AuthForm
    template_name = 'app_users/login.html'
    redirect_authenticated_user = True


class LogoutUserView(LogoutView):
    """
    Выход с сайта.
    """
    next_page = reverse_lazy('main_view')


class RegisterUserView(FormView):
    """
    Регистрация нового пользователя.
    """
    form_class = forms.RegisterForm
    template_name = 'app_users/register.html'
    success_url = reverse_lazy('main_view')

    def form_valid(self, form):
        services.create_new_user(form)
        user = services.authenticate_user(form)
        login(self.request, user)
        return super(RegisterUserView, self).form_valid(form)


class UserProfileView(LoginRequiredMixin, TemplateView):
    """
    Личная страница пользователя.
    """
    template_name = 'app_users/profile.html'
    login_url = reverse_lazy('app_users:login')
    extra_context = {
        forms.UserProfileCityForm.prefix: forms.UserProfileCityForm(),
        forms.UserProfileTelephoneForm.prefix: forms.UserProfileTelephoneForm(),
        forms.UserUsernameForm.prefix: forms.UserUsernameForm(),
        forms.UserEmailForm.prefix: forms.UserEmailForm(),
    }

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['pass_successfully_changed'] = self.request.GET.get('pass_successfully_changed')

        return context


class BaseUserUpdateView(UserProfileView, UpdateView):
    """
    Базовый класс для обновления данных пользователя.
    """
    success_url = reverse_lazy('app_users:profile')

    def get(self, request, *args, **kwargs):
        return redirect(reverse('app_users:profile'), permanent=True)

    def get_context_data(self, **kwargs):
        context = super(BaseUserUpdateView, self).get_context_data(**kwargs)
        context.update(**kwargs)

        return context

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(**{self.form_class.prefix: form}))


class UserProfileTelephoneUpdateView(BaseUserUpdateView):
    """
    Обновление номера телефона в профиле пользователя.
    """
    form_class = forms.UserProfileTelephoneForm
    model = models.UserProfile


class UserProfileCityUpdateView(BaseUserUpdateView):
    """
    Обновление города в профиле пользователя.
    """
    form_class = forms.UserProfileCityForm
    model = models.UserProfile


class UserUsernameUpdateView(BaseUserUpdateView):
    """
    Обновление имени пользователя.
    """
    form_class = forms.UserUsernameForm
    model = User


class UserEmailUpdateView(BaseUserUpdateView):
    """
    Обновление e-mail пользователя.
    """
    form_class = forms.UserEmailForm
    model = User


class UserChangePasswordView(PasswordChangeView):
    """
    Изменение пароля пользователя.
    """
    form_class = forms.UserChangePasswordForm
    success_url = reverse_lazy('app_users:profile')
    template_name = 'app_users/password_change.html'

    def get_success_url(self):
        url = super(UserChangePasswordView, self).get_success_url()
        return f"{url}?pass_successfully_changed=True"


class ModeratorMainView(ModeratorMixin, TemplateView):
    """
    Главная представление модерации.
    """
    template_name = 'app_users/main_moderation.html'


class ModerateUsersListView(ModeratorMixin, CustomPaginateListView, BaseFormsetUpdateView):
    """
    Представление для вывода всех пользователей для модераторов и возможностью массово менять статус пользователя.
    """
    template_name = 'app_users/users_list_moderation.html'
    queryset = models.UserProfile.objects.select_related('user')
    ordering = 'user'
    context_object_name = 'user_profiles'
    paginate_cookie_name = 'users_per_page'
    formset = UserProfileModerateFormSet

    def get_queryset(self):
        queryset = super(ModerateUsersListView, self).get_queryset()
        queryset = services.filter_users_queryset_by_username(queryset, self.request)
        queryset = services.filter_users_queryset_by_verification(queryset, self.request)

        return queryset


class UserModerateView(ModeratorMixin, generic.UpdateView):
    """
    Модерация пользователя, добавление статуса активности.
    """
    template_name = 'app_users/user_moderation.html'
    form_class = forms.UserProfileVerificationForm
    queryset = models.UserProfile.objects.select_related('user')
    context_object_name = 'user_profile'
    success_url = reverse_lazy('app_users:users_list_moderation')

news_portal-main/app_users/templates/app_users/main_moderation.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Главная страница модерации' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Главная страница модерации' %}</h2>
    <div class="center-content">
        <div class="center-content center-content_greeting">
            {% trans 'Модерация пользователей' users_moderate_trans %}
            <a class="update-link" href="{% url 'app_users:users_list_moderation' %}" aria-label="{{ users_moderate_trans }}" title="{{ users_moderate_trans }}">{{ users_moderate_trans }}</a>
            {% trans 'Модерация новостей' news_moderate_trans %}
            <a class="update-link" href="{% url 'app_news:news_list_moderation' %}" aria-label="{{ news_moderate_trans }}" title="{{ news_moderate_trans }}">{{ news_moderate_trans }}</a>
        </div>
    </div>
{% endblock %}

news_portal-main/app_users/templates/app_users/password_change.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Сменя пароля' %}
{%  endblock %}

{% block content %}
    {% trans 'Поменять пароль' as change_pass_trans %}
    <h2>{{ change_pass_trans }}</h2>
    <div class="center-content">
        <form method="post" action="{% url 'app_users:change_password' %}">
            {% include 'app_users/templates_for_include/login_register_form.html' with form=form%}
            <button type="submit" aria-label="{{ change_pass_trans }}" title="{{ change_pass_trans }}">{{ change_pass_trans }}</button>
        </form>
    </div>
{% endblock %}

news_portal-main/app_users/templates/app_users/profile.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% if request.user.is_authenticated %}
        {% trans 'Личный кабинет' %} {{ request.user.username }}
    {% else %}
        {% trans 'Вы еще не авторизованы' %}
    {% endif %}
{%  endblock %}

{% block content %}
    <div class="center-content">
        <div class="center-content center-content_greeting">
        {% if request.user.is_authenticated %}
            <h2>{% trans 'Личная информация' %}</h2>

            <div class="center-content center-content_with-border">
                <a href="{% url 'app_users:change_password' %}" class="update-link update-link_dark-theme">{% trans 'Поменять пароль' %}</a>
                {% if pass_successfully_changed %}
                    <p>{% trans 'Пароль успешно изменен' %}</p>
                {% endif %}
            </div>

            {% url 'app_users:update_username' pk=request.user.pk as username_update_url%}
            {% trans 'Имя пользователя' as username_trans %}
            {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=username_trans settings_value=request.user.username form=username_form url=username_update_url %}

            {% url 'app_users:update_email' pk=request.user.profile.pk as email_update_url %}
            {% trans 'Электронная почта' as email_trans %}
            {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=email_trans settings_value=request.user.email form=email_form url=email_update_url %}

            {% url 'app_users:update_city' pk=request.user.profile.pk as city_update_url%}
            {% trans 'Город' as city_trans %}
            {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=city_trans settings_value=request.user.profile.city form=city_form url=city_update_url %}

            {% url 'app_users:update_telephone' pk=request.user.profile.pk as telephone_update_url%}
            {% trans 'Номер телефона' as phone_number_trans %}
            {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=phone_number_trans settings_value=request.user.profile.telephone form=telephone_form url=telephone_update_url %}

            <div class="center-content center-content_with-border">
                <div class="settings-line">
                    <p class="settings-line__item_label">{% trans 'Количество созданных новостей' %}:</p>
                    <p class="settings-line__item_value">{{ request.user.profile.number_of_published_news }}</p>
                    {% if request.user.profile.number_of_published_news > 0%}
                        {% trans 'Список своих новостей' as self_news_list_trans %}
                        <a class="update-link update-link_dark-theme" href="{% url 'app_news:personal_news_list' %}" aria-label="{{ self_news_list_trans }}" title="{{ self_news_list_trans }}">{{ self_news_list_trans }}</a>
                    {% endif %}
                </div>
            </div>
            <div class="center-content">
                {% if request.user.profile.is_verified %}
                    {% trans 'Создать новостную сводку' as create_news_trans %}
                    <a class="update-link update-link_dark-theme" href="{% url 'app_news:news_create'%}" aria-label="{{ create_news_trans }}" title="{{ create_news_trans }}">{{ create_news_trans }}</a>
                {% else %}
                    <p>{% trans 'Вам не разрешено добавлять новости, обратитесь к администратору' %}</p>
                {% endif %}
            </div>
        {% else %}
            <h2>{% trans 'Вы еще не авторизованы' %}</h2>
        {% endif %}
        </div>
    </div>
{% endblock %}

news_portal-main/app_users/templates/app_users/register.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Регистрация на новостной портале' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Регистрация на новостной портале' %}</h2>
    <div class="center-content">
        <form method="post" action="{% url 'app_users:register' %}">
            {% include 'app_users/templates_for_include/login_register_form.html' %}
            {% trans 'Зарегистрироваться' as register_trans %}
            <button type="submit" aria-label="{{ register_trans }}" title="{{ register_trans }}">{{ register_trans }}</button>
        </form>
    </div>
{% endblock %}

news_portal-main/app_users/templates/app_users/user_moderation.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% block title %}
        {% trans 'Модерация пользователя' %} {{ user_profile.user.username }}
{% endblock %}

{% block content %}
    <div class="center-content">
        <div class="center-content center-content_greeting">
            {% trans 'Модерация пользователя' as moderate_user_trans%}
            {% with title_name=moderate_user_trans|add:' '|add:user_profile.user.username %}
                <h2>{{ title_name }}</h2>

                {% trans 'Имя пользователя' as username_trans %}
                {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=username_trans settings_value=user_profile.user.username %}
                {% trans 'Электронная почта' as email_trans %}
                {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=email_trans settings_value=user_profile.user.email %}
                {% trans 'Город' as city_trans %}
                {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=city_trans settings_value=user_profile.city %}
                {% trans 'Номер телефона' as phone_number_trans %}
                {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=phone_number_trans settings_value=user_profile.telephone %}
                {% trans 'Количество созданных новостей' as count_news_trans %}
                {% include 'app_users/templates_for_include/profile_settings_field.html' with settings_label=count_news_trans settings_value=user_profile.number_of_published_news %}

                <div class="center-content user-status {% if user_profile.is_verified %}user-status_verified{% else %}user-status_not-verified{% endif %}">
                    <form method="post" action="{% url 'app_users:user_moderation' pk=user_profile.id%}">
                        {% csrf_token %}

                        {% include 'project_modules/templates_for_include/scroling_to_field_with_errors.html' with label_id=form.is_verified.id_for_label %}

                        {{ form.as_p }}

                            <button type="submit" aria-label="{{ title_name }}" title="{{ title_name }}">{{ title_name }}</button>
                    </form>
                </div>
            {% endwith %}
        </div>
    </div>
{% endblock %}

news_portal-main/app_users/templates/app_users/users_list_moderation.html
{% extends 'project_modules/index.html' %}
{% load i18n %}

{% load static %}
{% load app_users_templatetags %}
{% load app_news_templatetags %}

{% block title %}
    {% trans 'Модерация пользователей' %}
{%  endblock %}

{% block content %}
    <h2>{% trans 'Модерация пользователей' %}</h2>

    <div class="object-filters object-filters_visible-filters">
        <label class="object-filters__fields">{% trans 'Показывать по' %}
            <select name="users_per_page">
                <option>3</option>
                <option>25</option>
                <option>50</option>
            </select>
        {% trans пользователей %}</label>
        {% trans 'Имя пользователя' as username_trans %}
        <label class="object-filters__fields">{{ username_trans }}
            {% trans 'Фильтр по имени пользователя' as filter_username_trans %}
            <input name="username" aria-label="{{ filter_username_trans }}" title="{{ filter_username_trans }}" placeholder="{{ username_trans }}">
        </label>
        <div class="object-filters__buttons">
            <button type="button" id="users_filter_apply">{% trans 'Применить фильтр' %}</button>
            <button type="button" id="users_filter_delete">{% trans 'Сбросить фильтр' %}</button>
        </div>
    </div>

    <script type="module">
        import {addCommonFilters} from '{% static 'project_modules/js/change_query_string.js' %}';

        document.addEventListener("DOMContentLoaded", function () {
            // Установка фильтров для отображаемых пользователей.
        addCommonFilters('users', ['username'])
        });
    </script>

    <script type="module">
        import {addStatusFilter} from '{% static 'project_modules/js/change_query_string.js' %}';

        document.addEventListener("DOMContentLoaded", function () {
            // Управление отображением пользователей по статусу верификации.
            addStatusFilter('displayed_users')
        });
    </script>

    <div class="object-filters">
        <a class="update-link object-filters__status-fields"><input name="displayed_news" type="radio" value="all">{% trans 'Все' %}</a>
        <a class="update-link object-filters__status-fields"><input name="displayed_news" type="radio" value="verified" >{% trans 'Только верифицированные' %}</a>
        <a class="update-link object-filters__status-fields"><input name="displayed_news" type="radio" value="not_verified">{% trans 'Только не верифицированные' %}</a>
    </div>

    {% include 'project_modules/templates_for_include/set_links_for_object_list_paginator.html' %}

    {% if user_profiles %}
        <form method="post" action="{{ request.get_full_path }}">
            {% csrf_token %}
            {{ formset.management_form }}
            {% include 'project_modules/templates_for_include/moderator_objects_paginator_links_list.html' %}

            <div>
                <ol class="object-list" start="{{ page_obj.start_index }}">
                    {% for user_profile, single_form in user_profiles|zip_lists:formset %}
                        <li class="object-list__item {% if not user_profile.is_verified %} object-list__item_without_status {% endif %}">
                            <div class="object-list__item-container">
                            {% trans 'Приступить к модерации пользователя' as usermaderate_begin_trans %}
                                <a class="object-list__link object-list__link_main-link" href="{% url 'app_users:user_moderation' pk=user_profile.pk%}" aria-label="{{ usermaderate_begin_trans }} {{ user_profile.user.username }}" title="{{ usermaderate_begin_trans }} {{ user_profile.user.username }}">
                                    <span class="object-list__link-context">{{ user_profile.user.username }}</span>

                                    {% if not user_profile.is_verified %}
                                        <span class="object-list__link-context">({% trans 'Пользователь еще не верифицирован' %})</span>
                                    {% endif %}


                                    <div class="object-list__info">
                                        <span class="object-list__link-context content-info">{% trans 'Телефон' %}: {{ user_profile.telephone }}</span>

                                        <span class="object-list__link-context content-info">
                                            {% trans 'Созданных новостей' %}: {{ user_profile.number_of_published_news }}
                                        </span>
                                    </div>
                                </a>

                                {{ single_form.non_field_errors }}
                                {{ single_form.id }}
                                {{ single_form.is_verified.errors }}
                                <label class="object-list__status-label">{% trans 'Статус пользователя' %}&nbsp;{{ single_form.is_verified }}</label>

                            </div>
                        </li>

                    {% endfor %}
                </ol>
            </div>

            {% include 'project_modules/templates_for_include/moderator_objects_paginator_links_list.html' %}
        </form>

    {% else %}
        <h2>{% trans 'Нет пользователей, удовлетворяющих вашему запросу' %}</h2>
    {% endif %}

{% endblock %}